// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets/en.json
var resourceEnJsonData []byte
var resourceEnJson = &fyne.StaticResource{
	StaticName:    "assets/en.json",
	StaticContent: resourceEnJsonData,
}

//go:embed assets/de.json
var resourceDeJsonData []byte
var resourceDeJson = &fyne.StaticResource{
	StaticName:    "assets/de.json",
	StaticContent: resourceDeJsonData,
}

//go:embed Icon.png
var resourceIconPngData []byte
var resourceIconPng = &fyne.StaticResource{
	StaticName:    "Icon.png",
	StaticContent: resourceIconPngData,
}
