name: OERC-Build

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  oerc-build:
    name: Project Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20' ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Make setup
        run: make setup

      - name: Make package
        run: make package
